name: Conlan Law
favicon: null
layout_spectrum: 0.59871
typography_spectrum: 0.8852522803936154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1592a'
    - '#818285'
    - '#ffffff'
    - '#000000'
    - '#6b2713'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
